---
title: "Data Sources"
output: github_document
---

### Quandl Free

**Zillow Real Estate Research**<br>
*Home prices and rents by size, type and tier; housing supply, demand and sales; sliced by zip code, neighborhood, city, metro area, county and state.*<br>
https://www.quandl.com/data/ZILLOW-Zillow-Real-Estate-Research<br>
<!-- https://www.quandl.com/api/v3/databases/ZILLOW/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**Federal Reserve Economic Data**<br>
*Growth, employment, inflation, labor, manufacturing and other US economic statistics from the research department of the Federal Reserve Bank of St. Louis.*<br>
https://www.quandl.com/data/FRED-Federal-Reserve-Economic-Data<br>
<!-- https://www.quandl.com/api/v3/databases/FRED/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**NASDAQ OMX Global Index Data**<br>
*Over 35,000 global indexes published by NASDAQ OMX including Global Equity, Fixed Income, Dividend, Green, Nordic, Sharia and more. Daily data.*<br>
https://www.quandl.com/data/NASDAQOMX-NASDAQ-OMX-Global-Index-Data<br>
<!-- https://www.quandl.com/api/v3/databases/NASDAQOMX/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**Yale Department of Economics**<br>
*Publishes data related to the stock and housing markets; price data for common indexes, interest rates, earnings, dividends, house prices, and CPI.*<br>
https://www.quandl.com/data/YALE-Yale-Department-of-Economics<br>
<!-- https://www.quandl.com/api/v3/databases/YALE/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**Consumer Sentiment**<br>
*The University of Michigan’s consumer survey, data points for the most recent 6 months are unofficial; they are sourced from articles in the Wall Street Journal.*<br>
https://www.quandl.com/data/UMICH-Consumer-Sentiment<br>
<!-- https://www.quandl.com/api/v3/databases/UMICH/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**S&P 500 Ratios**<br>
*No description for this database yet.*<br>
https://www.quandl.com/data/MULTPL-S-P-500-Ratios<br>
<!-- https://www.quandl.com/api/v3/databases/MULTPL/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**US Federal Reserve Data Releases**<br>
*Official US figures on money supply, interest rates, mortgages, government finances, bank assets and debt, exchange rates, industrial production.*<br>
https://www.quandl.com/data/FED-US-Federal-Reserve-Data-Releases<br>
<!-- https://www.quandl.com/api/v3/databases/FED/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**Freddie Mac**<br>
*Data from Freddie Mac’s Primary Mortgage Market Survey and other region specific historical mortgage rates.*<br>
https://www.quandl.com/data/FMAC-Freddie-Mac<br>
<!-- https://www.quandl.com/api/v3/databases/FMAC/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**Institute for Supply Management**<br>
*ISM promotes supply-chain management practices and publishes data on production and supply chains, new orders, inventories, and capital expenditures.*<br>
https://www.quandl.com/data/ISM-Institute-for-Supply-Management<br>
<!-- https://www.quandl.com/data/ISM-Institute-for-Supply-Management/usage/export<br> -->

 

**Association for Real Estate Securitization**<br>
*ARES protects investors, contributes to development of the real estate securitization product market, and facilitates expansion of the real estate investment market.*<br>
https://www.quandl.com/data/ARES-Association-for-Real-Estate-Securitization<br>
<!-- https://www.quandl.com/api/v3/databases/ARES/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**BLS Inflation & Prices**<br>
*US national and state-level inflation data, published by the Bureau of Labor Statistics.*<br>
https://www.quandl.com/data/BLSI-BLS-Inflation-Prices<br>
<!-- https://www.quandl.com/data/BLSI-BLS-Inflation-Prices/usage/export<br> -->

 

**BLS Employment & Unemployment**<br>
*US national and state-level employment and unemployment statistics, published by the Bureau of Labor Statistics.*<br>
https://www.quandl.com/data/BLSE-BLS-Employment-Unemployment<br>
<!-- https://www.quandl.com/api/v3/databases/BLSE/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**BLS Productivity**<br>
*US manufacturing, labor and business statistics, published by the Bureau of Labor Statistics.*<br>
https://www.quandl.com/data/BLSP-BLS-Productivity<br>
<!-- https://www.quandl.com/api/v3/databases/BLSP/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**BLS Pay & Benefits**<br>
*US work stoppage statistics, published by the Bureau of Labor Statistics.*<br>
https://www.quandl.com/data/BLSB-BLS-Pay-Benefits<br>
<!-- https://www.quandl.com/api/v3/databases/BLSB/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**Federal Reserve Bank of Philadelphia**<br>
*The FRBP is a regional central bank for the Federal Reserve. It publishes data on business confidence indexes, GDP, consumption, and other economic indicators.*<br>
https://www.quandl.com/data/FRBP-Federal-Reserve-Bank-of-Philadelphia<br>
<!-- https://www.quandl.com/api/v3/databases/FRBP/metadata?api_key=boSmRbTRhaZvsaPynN5n -->

 

**Investor Sentiment**<br>
*American Association of Individual Investor’s sentiment data.*<br>
https://www.quandl.com/data/AAII-Investor-Sentiment<br>
<!-- https://www.quandl.com/api/v3/databases/AAII/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**United States Misery Index**<br>
*Developed by economist Arthur Okun, the Misery Index is the unemployment rate added to the inflation rate.*<br>
https://www.quandl.com/data/USMISERY-United-States-Misery-Index<br>
<!-- https://www.quandl.com/api/v3/databases/USMISERY/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**Federal Reserve Bank of Cleveland**<br>
*The Federal Reserve Bank of Cleveland collects data from hundreds of financial institutions, including depository institutions, bank holding companies, and other entities that is used to assess financial institution conditions and also to glean insights into how the economy and financial system are doing.*<br>
https://www.quandl.com/data/FRBC-Federal-Reserve-Bank-of-Cleveland<br>
<!-- https://www.quandl.com/api/v3/databases/FRBC/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**Federal Deposit Insurance Corporation**<br>
*The FDIC is a federal insurer of bank deposits up to $250k and collects finance data on commercial banking and savings institutions.*<br>
https://www.quandl.com/data/FDIC-Federal-Deposit-Insurance-Corporation<br>
<!-- https://www.quandl.com/api/v3/databases/FDIC/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**US Treasury - Financial Management Service**<br>
*The monthly receipts/outlays and deficit/surplus of the United States of America.*<br>
https://www.quandl.com/data/FMSTREAS-US-Treasury-Financial-Management-Service<br>
<!-- https://www.quandl.com/api/v3/databases/FMSTREAS/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 

**Wells Fargo Home Mortgage Loans**<br>
*This database offers mortgage purchase and refinance rates from Wells Fargo Home Mortgage, a division of Wells Fargo Bank.*<br>
https://www.quandl.com/data/WFC-Wells-Fargo-Home-Mortgage-Loans<br>
<!-- https://www.quandl.com/api/v3/databases/WFC/metadata?api_key=boSmRbTRhaZvsaPynN5n<br> -->

 








